[INFO 2016-03-04-15:28:18 oauth2client.client Process-6] Attempting refresh to obtain initial access_token
[INFO 2016-03-04-15:28:18 oauth2client.client Process-6] Refreshing access_token
[INFO 2016-03-04-15:28:18 bigquery_etl.extract.gcloud_wrapper Process-6] StringIO
[INFO 2016-03-04-15:28:21 bigquery_etl.extract.utils Process-6] Converting  file to a dataframe
[ERROR 2016-03-04-15:28:27 bigquery_etl.extract.utils Process-6] Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.
